# Generated by Django 5.0.14 on 2025-11-27 01:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(db_index=True, help_text='API endpoint path (e.g., /api/analysis/analyze/)', max_length=255)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, PUT, DELETE, etc.)', max_length=10)),
                ('status_code', models.IntegerField(db_index=True, help_text='HTTP status code (200, 404, 500, etc.)')),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from request headers', null=True)),
                ('request_size_bytes', models.IntegerField(blank=True, help_text='Request body size in bytes', null=True)),
                ('response_size_bytes', models.IntegerField(blank=True, help_text='Response body size in bytes', null=True)),
                ('query_params', models.JSONField(blank=True, default=dict, help_text='URL query parameters as dictionary')),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when request was made')),
                ('user', models.ForeignKey(blank=True, help_text='User who made the request (null for unauthenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Access Log',
                'verbose_name_plural': 'API Access Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='analytics_api_user_created'), models.Index(fields=['endpoint', 'created_at'], name='analytics_api_endpoint_created'), models.Index(fields=['status_code', 'created_at'], name='analytics_api_status_created'), models.Index(fields=['created_at'], name='analytics_api_created')],
            },
        ),
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('signup', 'Sign Up'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('token_refresh', 'Token Refresh'), ('password_reset', 'Password Reset'), ('password_reset_request', 'Password Reset Request')], db_index=True, help_text='Type of authentication event', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address from which event originated', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('success', models.BooleanField(db_index=True, default=True, help_text='Whether the event was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if event failed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data (email used, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when event occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User associated with event (null for failed attempts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authentication_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authentication Log',
                'verbose_name_plural': 'Authentication Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='analytics_auth_user_created'), models.Index(fields=['event_type', 'created_at'], name='analytics_auth_event_created'), models.Index(fields=['success', 'created_at'], name='analytics_auth_success_created'), models.Index(fields=['ip_address', 'created_at'], name='analytics_auth_ip_created')],
            },
        ),
        migrations.CreateModel(
            name='ExternalAPICallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('gemini', 'Google Gemini'), ('brightdata', 'BrightData'), ('supabase', 'Supabase')], db_index=True, help_text='External service name', max_length=20)),
                ('endpoint', models.CharField(help_text='External API endpoint URL', max_length=500)),
                ('method', models.CharField(help_text='HTTP method used', max_length=10)),
                ('status_code', models.IntegerField(help_text='HTTP status code from external API')),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=6, help_text='Estimated cost in USD', max_digits=10, null=True)),
                ('request_size_bytes', models.IntegerField(blank=True, help_text='Request payload size in bytes', null=True)),
                ('response_size_bytes', models.IntegerField(blank=True, help_text='Response payload size in bytes', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if call failed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (model used, tokens, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when API call was made')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the API call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_api_call_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External API Call Log',
                'verbose_name_plural': 'External API Call Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'service', 'created_at'], name='analytics_ext_user_service'), models.Index(fields=['service', 'created_at'], name='analytics_ext_service_created'), models.Index(fields=['created_at'], name='analytics_ext_created')],
            },
        ),
    ]
