# Generated by Django 5.0.14 on 2025-11-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalapicalllog',
            name='service',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('brightdata', 'BrightData'), ('twitterapi', 'TwitterAPI.io'), ('supabase', 'Supabase')], db_index=True, help_text='External service name', max_length=20),
        ),
    ]
