"""
Django settings for postbro project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import dj_database_url

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        'SECRET_KEY environment variable is required. '
        'Please set it in your .env file or environment variables.'
    )

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for safety - explicitly set DEBUG=True in .env for development
DEBUG = os.getenv('DEBUG', '').lower() == 'true'

# Allow ngrok domains for local webhook testing
_default_hosts = 'localhost,127.0.0.1'
_allowed_hosts = os.getenv('ALLOWED_HOSTS', _default_hosts).split(',')

# Add ngrok domain from environment variable if provided (for local development)
# Set NGROK_DOMAIN in .env if using ngrok for webhook testing
ngrok_domain = os.getenv('NGROK_DOMAIN')
if ngrok_domain and DEBUG:
    _allowed_hosts.append(ngrok_domain.strip())

ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django_celery_beat',
    'django_celery_results',
    
    # Local apps
    'accounts.apps.AccountsConfig',
    'social.apps.SocialConfig',
    'analysis.apps.AnalysisConfig',
    'feedback.apps.FeedbackConfig',
    'billing.apps.BillingConfig',
    'logs.apps.LogsConfig',
    'analytics.apps.AnalyticsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'postbro.middleware.AllowNgrokHostsMiddleware',  # Allow ngrok domains in DEBUG mode
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'analytics.middleware.APITrackingMiddleware',  # After AuthenticationMiddleware to access request.user
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'postbro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'postbro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Use Supabase database connection from .env
SUPABASE_DB_URL = os.getenv('SUPABASE_DB_URL')

if SUPABASE_DB_URL:
    # Connect to Supabase PostgreSQL
    DATABASES = {
        'default': dj_database_url.config(
            default=SUPABASE_DB_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Fallback to local database (for development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'postbro'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'accounts.authentication.ClerkAuthentication',  # Use Clerk auth
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # Throttle rates for specific endpoints (selective throttling)
    # Note: We don't use DEFAULT_THROTTLE_CLASSES to avoid throttling all endpoints
    # Instead, we apply throttling selectively to expensive operations only
    'DEFAULT_THROTTLE_RATES': {
        'analyze': '20/hour',      # 20 analyses per hour per user
        'chat': '100/hour',        # 100 chat messages per hour per user
    }
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    origin.strip() 
    for origin in os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')
]

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@postbro.com'

# Celery settings
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# Django AllAuth settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'accounts.backends.EmailBackend',  # Custom backend for email authentication
]

SITE_ID = 1

# Updated AllAuth settings
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SESSION_REMEMBER = True

# Logging settings - Production ready for Docker
# Docker handles log rotation, so we only log to stdout/stderr
# All errors must include analysis_request_id or chat_session_id for tracing
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} [{name}] {process:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'stream': 'ext://sys.stdout',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',  # Reduce Django noise
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',  # Only log request errors
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'ERROR',  # Don't log SQL queries
            'propagate': False,
        },
        'postbro': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'analysis': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'social': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Remove file logging - Docker handles it
# No need to create logs directory in production

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Clerk Configuration
CLERK_PUBLISHABLE_KEY = os.getenv('CLERK_PUBLISHABLE_KEY')
CLERK_SECRET_KEY = os.getenv('CLERK_SECRET_KEY')
CLERK_FRONTEND_URL = os.getenv('CLERK_FRONTEND_URL', 'http://localhost:3000')

# Supabase Configuration (for database only, not auth)
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_PUBLISHABLE_KEY = os.getenv('SUPABASE_PUBLISHABLE_KEY')
SUPABASE_SECRET_KEY = os.getenv('SUPABASE_SECRET_KEY')

# Fallback to legacy keys if new keys not provided
if not SUPABASE_PUBLISHABLE_KEY:
    SUPABASE_PUBLISHABLE_KEY = os.getenv('SUPABASE_KEY')
if not SUPABASE_SECRET_KEY:
    SUPABASE_SECRET_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY')

# Gemini API Configuration (Multiple keys for rotation)
# Supports GEMINI_API_KEY_1, GEMINI_API_KEY_2, GEMINI_API_KEY_3, etc.
# Also supports single GEMINI_API_KEY for backward compatibility
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
GEMINI_API_KEY_1 = os.getenv('GEMINI_API_KEY_1')
GEMINI_API_KEY_2 = os.getenv('GEMINI_API_KEY_2')
GEMINI_API_KEY_3 = os.getenv('GEMINI_API_KEY_3')
GEMINI_API_KEY_4 = os.getenv('GEMINI_API_KEY_4')
GEMINI_API_KEY_5 = os.getenv('GEMINI_API_KEY_5')

# AI Provider Configuration
# Options: 'gemini' (default) or 'self_hosted'
AI_PROVIDER = os.getenv('AI_PROVIDER', 'gemini')

# Self-Hosted LLM Configuration (if using self_hosted provider)
SELF_HOSTED_LLM_URL = os.getenv('SELF_HOSTED_LLM_URL', 'http://localhost:8000')
SELF_HOSTED_LLM_MODEL = os.getenv('SELF_HOSTED_LLM_MODEL', 'llama3')
SELF_HOSTED_LLM_API_KEY = os.getenv('SELF_HOSTED_LLM_API_KEY', None)
