# Generated by Django 5.0.14 on 2025-11-23 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnalysisRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('x', 'X (Twitter)')], max_length=20)),
                ('username', models.CharField(blank=True, help_text='Username/handle to analyze', max_length=255, null=True)),
                ('post_urls', models.JSONField(blank=True, default=list, help_text='List of specific post URLs to analyze')),
                ('date_range_type', models.CharField(blank=True, choices=[('last_7_days', 'Last 7 Days'), ('last_14_days', 'Last 14 Days'), ('last_30_days', 'Last 30 Days')], help_text='Date range for analysis (only used with username)', max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Start date for analysis', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date for analysis', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=255, null=True)),
                ('results', models.JSONField(blank=True, default=dict, help_text='AI analysis results')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='analysis_po_user_id_97e5c9_idx'), models.Index(fields=['status'], name='analysis_po_status_fed0a7_idx'), models.Index(fields=['platform'], name='analysis_po_platfor_d038cd_idx')],
            },
        ),
    ]
