# Generated by Django 5.0.14 on 2025-11-24 22:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanalysisrequest',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last retry attempt', null=True),
        ),
        migrations.AddField(
            model_name='postanalysisrequest',
            name='max_retries',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of retry attempts allowed'),
        ),
        migrations.AddField(
            model_name='postanalysisrequest',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this request has been retried'),
        ),
        migrations.AlterField(
            model_name='postanalysisrequest',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('x', 'X (Twitter)'), ('youtube', 'YouTube')], max_length=20),
        ),
        migrations.CreateModel(
            name='AnalysisStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('request_created', 'Request Created'), ('fetching_social_data', 'Fetching Social Data'), ('social_data_fetched', 'Social Data Fetched'), ('displaying_content', 'Displaying Content'), ('analyzing_posts', 'PostBro is analyzing these posts'), ('analysis_complete', 'Analysis Complete'), ('partial_success', 'Partial Success'), ('error', 'Error Occurred'), ('retrying', 'Retrying...')], help_text='Current stage of the analysis process', max_length=50)),
                ('message', models.TextField(help_text='Human-readable status message displayed to the user')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data: post_count, post_ids, error_details, etc.')),
                ('is_error', models.BooleanField(default=False, help_text='Whether this status represents an error')),
                ('error_code', models.CharField(blank=True, help_text='Machine-readable error code (e.g., RATE_LIMIT, INVALID_URL)', max_length=50, null=True)),
                ('retryable', models.BooleanField(default=False, help_text='Whether the user can retry this operation')),
                ('actionable_message', models.TextField(blank=True, help_text='Actionable message telling the user what they can do', null=True)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Duration of this stage in seconds', null=True)),
                ('api_calls_made', models.IntegerField(default=0, help_text='Number of API calls made during this stage')),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=4, help_text='Estimated cost in USD for this stage', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_request', models.ForeignKey(help_text='The analysis request this status belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='analysis.postanalysisrequest')),
            ],
            options={
                'verbose_name': 'Analysis Status History',
                'verbose_name_plural': 'Analysis Status Histories',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['analysis_request', 'created_at'], name='analysis_an_analysi_0abff8_idx'), models.Index(fields=['stage', 'is_error'], name='analysis_an_stage_934c4c_idx'), models.Index(fields=['created_at'], name='analysis_an_created_6b762e_idx')],
            },
        ),
    ]
