# Generated by Django 5.0.14 on 2025-11-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_add_youtube_retry_and_status_history'),
        ('social', '0004_add_supabase_storage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanalysisrequest',
            name='posts',
            field=models.ManyToManyField(blank=True, help_text='Posts analyzed in this request (enables post reuse/caching)', related_name='analysis_requests', to='social.post'),
        ),
    ]
