# Generated by Django 5.0.14 on 2025-11-25 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_add_posts_manytomany'),
        ('social', '0004_add_supabase_storage_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postanalysisrequest',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name extracted from posts (for sidebar/title). Set automatically when social data is fetched.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postanalysisrequest',
            name='username',
            field=models.CharField(blank=True, help_text='Username/handle to analyze (input field)', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='postanalysisrequest',
            index=models.Index(fields=['display_name'], name='analysis_po_display_9f155c_idx'),
        ),
    ]
