# Generated by Django 5.0.14 on 2025-11-26 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_backfill_display_name'),
        ('social', '0004_add_supabase_storage_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(help_text='Task ID from prompt', max_length=255)),
                ('is_viral', models.BooleanField(default=False, help_text='Whether the post is viral')),
                ('virality_reasoning', models.TextField(blank=True, help_text='Reasoning for virality (max 120 words)')),
                ('analysis_data', models.JSONField(default=dict, help_text='Analysis data: strengths, weaknesses, deep_analysis (hook, structure, psychology)')),
                ('improvements', models.JSONField(default=list, help_text='List of improvement suggestions (max 25 words each)')),
                ('suggestions_for_future_posts', models.JSONField(default=list, help_text='List of 4 future post suggestions with hook, outline, why_it_works')),
                ('metadata_used', models.JSONField(default=dict, help_text='Metadata used in analysis: username, posted_at, requested_at, media_count, platform_metrics')),
                ('llm_model', models.CharField(default='gemini-2.0-flash-exp', help_text='LLM model used', max_length=50)),
                ('llm_response_raw', models.TextField(blank=True, help_text='Raw JSON response from LLM')),
                ('processing_time_seconds', models.FloatField(blank=True, help_text='Time taken to process', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_request', models.ForeignKey(help_text='The analysis request this post analysis belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='post_analyses', to='analysis.postanalysisrequest')),
                ('post', models.ForeignKey(help_text='The post being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='social.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['analysis_request', 'created_at'], name='analysis_po_analysi_bd91e2_idx'), models.Index(fields=['post'], name='analysis_po_post_id_6ad9df_idx')],
                'unique_together': {('analysis_request', 'post')},
            },
        ),
    ]
