# Generated by Django 5.0.14 on 2025-11-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_postanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanalysis',
            name='content_observation',
            field=models.JSONField(blank=True, default=dict, help_text='Content observation: caption_observation, visual_observation, engagement_context, platform_signals'),
        ),
        migrations.AlterField(
            model_name='postanalysis',
            name='analysis_data',
            field=models.JSONField(default=dict, help_text='Analysis data: platform, framework_used, strengths, weaknesses, deep_analysis (hook, structure, psychology)'),
        ),
        migrations.AlterField(
            model_name='postanalysis',
            name='virality_reasoning',
            field=models.TextField(blank=True, help_text='Reasoning for virality (max 150 words)'),
        ),
    ]
