# Generated by Django 5.0.14 on 2025-11-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_add_content_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanalysis',
            name='quick_takeaways',
            field=models.JSONField(blank=True, default=list, help_text="3-5 bullet points summarizing key reasons it went viral (or why it didn't)"),
        ),
        migrations.AddField(
            model_name='postanalysis',
            name='replicable_elements',
            field=models.JSONField(blank=True, default=list, help_text='Prescriptive replicable elements: "Hook type: [X] → works for [Y]" format'),
        ),
        migrations.AddField(
            model_name='postanalysis',
            name='viral_formula',
            field=models.TextField(blank=True, help_text='1-2 line summary of viral formula or improvement formula'),
        ),
    ]
