# Generated by Django 5.0.14 on 2025-11-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_add_quick_takeaways_replicable_viral_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postanalysisrequest',
            name='date_range_type',
        ),
        migrations.RemoveField(
            model_name='postanalysisrequest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='postanalysisrequest',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='postanalysisrequest',
            name='username',
        ),
        migrations.AlterField(
            model_name='postanalysisrequest',
            name='post_urls',
            field=models.JSONField(default=list, help_text='List of specific post URLs to analyze (required)'),
        ),
    ]
