# Generated by Django 5.0.14 on 2025-11-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_remove_username_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanalysis',
            name='creator_context',
            field=models.TextField(blank=True, help_text='Who is this creator? (celebrity, influencer, brand, etc.) If they have a large following, identify them by name. Their influence level and niche.'),
        ),
    ]
