# Generated by Django 5.0.14 on 2025-12-01 00:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_add_creator_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', help_text='Session status (active or archived)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_analysis', models.OneToOneField(help_text='The post analysis this chat session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_session', to='analysis.postanalysis')),
                ('user', models.ForeignKey(help_text='User who owns this chat session', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], help_text='Message role: user or assistant', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens used for this message (for analytics)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='The chat session this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analysis.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'status'], name='analysis_ch_user_id_25549f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['post_analysis'], name='analysis_ch_post_an_a37750_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['updated_at'], name='analysis_ch_updated_f6cdcd_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='analysis_ch_session_24ea69_idx'),
        ),
    ]
