# Generated by Django 5.0.14 on 2025-12-03 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_add_analysis_completed_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisstatushistory',
            name='stage',
            field=models.CharField(choices=[('request_created', 'Request Created'), ('fetching_posts', 'Fetching Posts'), ('fetching_social_data', 'Fetching Social Data'), ('social_data_fetched', 'Social Data Fetched'), ('collecting_media', 'Collecting Media'), ('transcribing', 'Transcribing Audio'), ('displaying_content', 'Displaying Content'), ('analyzing_posts', 'PostBro is analyzing these posts'), ('analysing', 'Analysing'), ('analysis_complete', 'Analysis Complete'), ('partial_success', 'Partial Success'), ('error', 'Error Occurred'), ('retrying', 'Retrying...')], help_text='Current stage of the analysis process', max_length=50),
        ),
        migrations.CreateModel(
            name='AnalysisNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Note title', max_length=200)),
                ('content', models.TextField(help_text='Note content (ideas, strategies, insights, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_analysis', models.ForeignKey(help_text='The post analysis this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='analysis.postanalysis')),
                ('user', models.ForeignKey(help_text='User who created this note', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'post_analysis'], name='analysis_an_user_id_fe6a43_idx'), models.Index(fields=['post_analysis', '-updated_at'], name='analysis_an_post_an_782940_idx')],
                'unique_together': {('user', 'post_analysis')},
            },
        ),
    ]
