# Generated by Django 5.0.14 on 2025-12-03 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_add_analysis_note'),
        ('social', '0006_add_business_metrics_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='duration_seconds',
            field=models.FloatField(blank=True, help_text='Time from first to last message in seconds (calculated on session close)', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='messages_count',
            field=models.IntegerField(default=0, help_text='Total number of messages in this session (updated on message creation)'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='total_tokens',
            field=models.IntegerField(blank=True, help_text='Total tokens used across all messages in this session', null=True),
        ),
        migrations.AddField(
            model_name='postanalysisrequest',
            name='duration_seconds',
            field=models.FloatField(blank=True, help_text='Total processing duration in seconds (calculated after completion)', null=True),
        ),
        migrations.AddField(
            model_name='postanalysisrequest',
            name='error_category',
            field=models.CharField(blank=True, choices=[('rate_limit', 'Rate Limit Exceeded'), ('api_error', 'External API Error'), ('network_error', 'Network Error'), ('validation_error', 'Validation Error'), ('processing_error', 'Processing Error'), ('timeout', 'Request Timeout'), ('quota_exceeded', 'Quota Exceeded'), ('unknown', 'Unknown Error')], help_text='Internal: Category of error (not exposed to users)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postanalysisrequest',
            name='error_details',
            field=models.JSONField(blank=True, default=dict, help_text='Internal: Detailed error information for debugging (exception type, traceback, etc.)'),
        ),
        migrations.AddField(
            model_name='postanalysisrequest',
            name='error_stage',
            field=models.CharField(blank=True, choices=[('social_collection', 'Social Media Collection'), ('media_extraction', 'Media Extraction & Upload'), ('gemini_analysis', 'Gemini API Analysis')], help_text='Internal: Stage where error occurred (not exposed to users)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postanalysisrequest',
            name='failed_at_stage',
            field=models.CharField(blank=True, help_text='Internal: Last successful stage before failure (for smart retry)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postanalysisrequest',
            name='posts_processed',
            field=models.IntegerField(default=0, help_text='Number of posts successfully processed'),
        ),
        migrations.AddField(
            model_name='postanalysisrequest',
            name='total_api_calls',
            field=models.IntegerField(default=0, help_text='Total number of external API calls made during processing'),
        ),
        migrations.AlterField(
            model_name='postanalysisrequest',
            name='error_message',
            field=models.TextField(blank=True, help_text='User-friendly error message if processing failed', null=True),
        ),
        migrations.AddIndex(
            model_name='postanalysisrequest',
            index=models.Index(fields=['error_stage', 'error_category'], name='analysis_po_error_s_34b109_idx'),
        ),
        migrations.AddIndex(
            model_name='postanalysisrequest',
            index=models.Index(fields=['status', 'retry_count'], name='analysis_po_status_7b3d38_idx'),
        ),
    ]
