# Generated by Django 5.0.14 on 2025-11-23 22:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_remove_user_email_verification_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_method_id', models.CharField(help_text='Stripe PaymentMethod ID', max_length=255, unique=True)),
                ('type', models.CharField(help_text='card, bank_account, etc.', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='Default payment method for user')),
                ('card_brand', models.CharField(blank=True, help_text='visa, mastercard, etc.', max_length=50)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_exp_month', models.IntegerField(blank=True, null=True)),
                ('card_exp_year', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional Stripe data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete when removed from Stripe', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in cents (e.g., 2999 = $29.99)', max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('payment_type', models.CharField(choices=[('subscription', 'Subscription Payment'), ('one_time', 'One-Time Payment'), ('upgrade', 'Plan Upgrade'), ('refund', 'Refund')], default='subscription', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for payment failure', null=True)),
                ('failure_code', models.CharField(blank=True, help_text='Stripe error code', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Payment description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional Stripe data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment succeeded', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='When payment failed', null=True)),
                ('subscription', models.ForeignKey(blank=True, help_text='Null for one-time payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.paymentmethod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_refund_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount in cents', max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('reason', models.CharField(blank=True, help_text='Reason for refund', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='billing.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(help_text='Stripe Event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(choices=[('subscription.created', 'Subscription Created'), ('subscription.updated', 'Subscription Updated'), ('subscription.deleted', 'Subscription Deleted'), ('subscription.renewed', 'Subscription Renewed'), ('payment_intent.succeeded', 'Payment Succeeded'), ('payment_intent.payment_failed', 'Payment Failed'), ('charge.succeeded', 'Charge Succeeded'), ('charge.failed', 'Charge Failed'), ('charge.refunded', 'Charge Refunded'), ('invoice.created', 'Invoice Created'), ('invoice.paid', 'Invoice Paid'), ('invoice.payment_failed', 'Invoice Payment Failed'), ('invoice.upcoming', 'Invoice Upcoming'), ('customer.created', 'Customer Created'), ('customer.updated', 'Customer Updated'), ('payment_method.attached', 'Payment Method Attached'), ('payment_method.detached', 'Payment Method Detached')], max_length=100)),
                ('event_data', models.JSONField(default=dict, help_text='Full Stripe event object')),
                ('processed', models.BooleanField(default=False, help_text='Whether we successfully processed this event')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_events', to='accounts.subscription')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='billing_bil_user_id_ee53d1_idx'), models.Index(fields=['stripe_event_id'], name='billing_bil_stripe__b2aeb1_idx'), models.Index(fields=['event_type', 'created_at'], name='billing_bil_event_t_586f4d_idx'), models.Index(fields=['processed'], name='billing_bil_process_711d6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_invoice_id', models.CharField(max_length=255, unique=True)),
                ('stripe_invoice_number', models.CharField(blank=True, help_text='Human-readable invoice number', max_length=255)),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Amount due in cents', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid in cents', max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], default='draft', max_length=20)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, help_text='Invoice date')),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When invoice was paid', null=True)),
                ('invoice_pdf_url', models.URLField(blank=True, help_text='Stripe invoice PDF URL', max_length=500)),
                ('invoice_data', models.JSONField(blank=True, default=dict, help_text='Full Stripe invoice object')),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(blank=True, help_text='Null for one-time invoices', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='accounts.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='billing.payment')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'invoice_date'], name='billing_inv_user_id_1f29f8_idx'), models.Index(fields=['subscription', 'invoice_date'], name='billing_inv_subscri_1e8357_idx'), models.Index(fields=['status'], name='billing_inv_status_541249_idx'), models.Index(fields=['stripe_invoice_id'], name='billing_inv_stripe__1798ef_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'is_default'], name='billing_pay_user_id_6127f5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['stripe_payment_method_id'], name='billing_pay_stripe__44aa09_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'created_at'], name='billing_pay_user_id_c2eb92_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['subscription', 'created_at'], name='billing_pay_subscri_ce053d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='billing_pay_status_b7739e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='billing_pay_stripe__5c9ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_charge_id'], name='billing_pay_stripe__b4a1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['payment', 'created_at'], name='billing_ref_payment_d4f37e_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['user', 'created_at'], name='billing_ref_user_id_5cec5f_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['stripe_refund_id'], name='billing_ref_stripe__86d03b_idx'),
        ),
    ]
