# Generated by Django 5.0.14 on 2025-12-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_make_payment_fields_generic'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='billing_pay_provider_ch_idx',
        ),
        migrations.RenameIndex(
            model_name='billingevent',
            new_name='billing_bil_provide_0d1fc8_idx',
            old_name='billing_bil_provider_evt_id_idx',
        ),
        migrations.RenameIndex(
            model_name='billingevent',
            new_name='billing_bil_payment_f5a376_idx',
            old_name='billing_bil_provider_evt_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_provide_e6a7ea_idx',
            old_name='billing_inv_provider_inv_id_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='billing_inv_payment_9df1ce_idx',
            old_name='billing_inv_provider_inv_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_provide_60dbd4_idx',
            old_name='billing_pay_provider_pi_id_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_provide_a4f945_idx',
            old_name='billing_pay_provider_ch_id_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_payment_0ba2d3_idx',
            old_name='billing_pay_provider_pi_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmethod',
            new_name='billing_pay_provide_fafc46_idx',
            old_name='billing_pay_provider_pm_id_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmethod',
            new_name='billing_pay_payment_c395d1_idx',
            old_name='billing_pay_provider_pm_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='billing_ref_provide_91cbea_idx',
            old_name='billing_ref_provider_ref_id_idx',
        ),
        migrations.RenameIndex(
            model_name='refund',
            new_name='billing_ref_payment_95f619_idx',
            old_name='billing_ref_provider_ref_idx',
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='event_type',
            field=models.CharField(choices=[('subscription.created', 'Subscription Created'), ('subscription.updated', 'Subscription Updated'), ('subscription.deleted', 'Subscription Deleted'), ('subscription.renewed', 'Subscription Renewed'), ('payment_intent.succeeded', 'Payment Succeeded'), ('payment_intent.payment_failed', 'Payment Failed'), ('charge.succeeded', 'Charge Succeeded'), ('charge.failed', 'Charge Failed'), ('charge.refunded', 'Charge Refunded'), ('invoice.created', 'Invoice Created'), ('invoice.paid', 'Invoice Paid'), ('invoice.payment_failed', 'Invoice Payment Failed'), ('invoice.upcoming', 'Invoice Upcoming'), ('customer.created', 'Customer Created'), ('customer.updated', 'Customer Updated'), ('payment_method.attached', 'Payment Method Attached'), ('payment_method.detached', 'Payment Method Detached'), ('checkout.session.completed', 'Checkout Session Completed'), ('subscription.active', 'Subscription Active'), ('subscription.on_hold', 'Subscription On Hold')], max_length=100),
        ),
        migrations.AlterField(
            model_name='billingevent',
            name='provider_event_id',
            field=models.CharField(help_text='Payment provider Event ID (e.g., Stripe evt_xxx or Dodo event ID)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='provider_invoice_id',
            field=models.CharField(help_text='Payment provider Invoice ID (e.g., Stripe in_xxx or Dodo invoice ID)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_charge_id',
            field=models.CharField(blank=True, help_text='Payment provider Charge ID (e.g., Stripe ch_xxx or Dodo charge ID)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_payment_intent_id',
            field=models.CharField(blank=True, help_text='Payment provider PaymentIntent ID (e.g., Stripe pi_xxx or Dodo payment ID)', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider_payment_method_id',
            field=models.CharField(help_text='Payment provider PaymentMethod ID (e.g., Stripe pm_xxx or Dodo pm_xxx)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='provider_refund_id',
            field=models.CharField(help_text='Payment provider Refund ID (e.g., Stripe re_xxx or Dodo refund ID)', max_length=255, unique=True),
        ),
    ]
