# Generated by Django 5.0.14 on 2025-11-23 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('twitter', 'Twitter'), ('instagram', 'Instagram')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_post_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('engagement_score', models.FloatField(default=0.0)),
                ('metrics', models.JSONField(default=dict)),
                ('url', models.URLField(max_length=2048)),
                ('posted_at', models.DateTimeField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social.platform')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('video_thumbnail', 'Video Thumbnail')], max_length=20)),
                ('file', models.FileField(upload_to='post_media/')),
                ('source_url', models.URLField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='social.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPostActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('handle', 'Handle'), ('url', 'URL')], max_length=10)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='social.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['engagement_score'], name='social_post_engagem_7d6560_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['username'], name='social_post_usernam_e1496a_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['platform'], name='social_post_platfor_6508d9_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['posted_at'], name='social_post_posted__ca8c7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('platform', 'platform_post_id')},
        ),
        migrations.AddIndex(
            model_name='userpostactivity',
            index=models.Index(fields=['user', 'viewed_at'], name='social_user_user_id_10cbe1_idx'),
        ),
    ]
