# Generated by Django 5.0.14 on 2025-11-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='formatted_transcript',
            field=models.JSONField(blank=True, default=list, help_text='Timestamped transcript segments with start_time, end_time, duration, text'),
        ),
        migrations.AddField(
            model_name='post',
            name='transcript',
            field=models.TextField(blank=True, help_text='Full transcript text (YouTube videos only)', null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=50, unique=True),
        ),
    ]
