# Generated by Django 5.0.14 on 2025-11-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_add_youtube_platform_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='supabase_url',
            field=models.URLField(blank=True, help_text='Supabase Storage URL (if uploaded)', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='uploaded_to_supabase',
            field=models.BooleanField(default=False, help_text='Whether this media has been uploaded to Supabase Storage'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post_media/'),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('video_thumbnail', 'Video Thumbnail'), ('video_frame', 'Video Frame')], max_length=20),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='source_url',
            field=models.URLField(help_text='Original API URL', max_length=2048),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['uploaded_to_supabase'], name='social_post_uploade_e48843_idx'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['post', 'media_type'], name='social_post_post_id_744c28_idx'),
        ),
    ]
