# Generated by Django 5.0.14 on 2025-12-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_add_transcript_to_postmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='formatted_transcript',
            field=models.JSONField(blank=True, default=list, help_text='Timestamped transcript segments with start_time, end_time, duration, text (YouTube only)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='transcript',
            field=models.TextField(blank=True, help_text='Full transcript text (from YouTube API or Whisper AI for Instagram/Twitter videos)', null=True),
        ),
    ]
