# Generated by Django 5.0.14 on 2025-06-15 13:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=10)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('scrape', 'Scraping'), ('api', 'API'), ('analysis', 'Analysis'), ('billing', 'Billing'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level'], name='logs_applog_level_339be2_idx'), models.Index(fields=['category'], name='logs_applog_categor_4e5bd4_idx'), models.Index(fields=['created_at'], name='logs_applog_created_ee2c88_idx')],
            },
        ),
    ]
