# Generated by Django 5.0.14 on 2025-11-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_create_default_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token',
        ),
        migrations.AddField(
            model_name='user',
            name='supabase_user_id',
            field=models.UUIDField(blank=True, help_text='Supabase auth.users ID', null=True, unique=True),
        ),
    ]
