# Generated by Django 5.0.14 on 2025-12-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_clerk_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_questions_per_day',
            field=models.PositiveIntegerField(default=10, help_text='Maximum chat questions per day'),
        ),
        migrations.AddField(
            model_name='userusage',
            name='questions_asked',
            field=models.PositiveIntegerField(default=0, help_text='Number of chat questions asked today'),
        ),
        migrations.AlterField(
            model_name='user',
            name='supabase_user_id',
            field=models.UUIDField(blank=True, help_text='Supabase auth.users ID (deprecated)', null=True, unique=True),
        ),
    ]
