# Generated by Django 5.0.14 on 2025-12-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_make_subscription_fields_generic'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='accounts_sub_provider_cust_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='accounts_sub_provider_sub_id_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='accounts_su_payment_49430e_idx',
            old_name='accounts_sub_provider_cust_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='accounts_su_payment_d5a03a_idx',
            old_name='accounts_sub_provider_sub_idx',
        ),
        migrations.AddField(
            model_name='plan',
            name='provider_product_id',
            field=models.CharField(blank=True, help_text='Payment provider Product ID (e.g., Dodo product_id or Stripe price_id)', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider_customer_id',
            field=models.CharField(blank=True, help_text='Payment provider Customer ID (e.g., Stripe cus_xxx or Dodo customer ID)', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='provider_subscription_id',
            field=models.CharField(blank=True, help_text='Payment provider Subscription ID (e.g., Stripe sub_xxx or Dodo subscription ID)', max_length=255),
        ),
    ]
