# Generated by Django 5.0.14 on 2025-12-05 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_canceling_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='downgrade_to_plan',
            field=models.ForeignKey(blank=True, help_text='Plan to downgrade to when current period ends (only set when status is CANCELING for downgrades)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_downgrades', to='accounts.plan'),
        ),
    ]
